---
debug: true
production: true
# can only do one cluster - v1
k8s_api_server_addr: "10.110.8.4"
k8s_api_server_port: "6443"
k8s_api_server: "https://{{ k8s_api_server_addr }}:{{ k8s_api_server_port }}"
k8s_client_certificate: "/etc/prometheus/ca.crt"
k8s_bearer_token: "/etc/prometheus/bearer.token"
localuser: ubuntu
gateway_host: terminus

prometheus_alertmanager_url: http://monitoring.skao.stfc:9093
prometheus_url: https://monitoring.skao.stfc:9090
slack_channel: psi-mid-alerts
slack_channel_user: psi-mid-user-alerts

k8s_external_dns_entry: 

grafana_disable_admin_account_creation: "false"

project_name: "PSI-Mid"

prometheus_datacentre: psi-mid-monitor

prometheus_global:
  scrape_interval: 15s
  scrape_timeout: 5s
  evaluation_interval: 15s

prometheus_static_node_metric_relabel_configs:
  - action: replace
    regex: 192\.168\.99\.194:9100
    replacement: terminus:9100
    source_labels:
    - instance
    target_label: instance

prometheus_scrape_configs:
  - job_name: "prometheus"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"

  - job_name: "gitlab_ci_pipelines_exporter"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:8080"

  - job_name: "node"
    file_sd_configs:
    - files:
      - 'node_exporter.json'
    metric_relabel_configs: "{{ elasticsearch_instance_add_cluster_label + prometheus_node_metric_relabel_configs }}"

  - job_name: "gitlab-runner"
    static_configs:
    - targets:
      - "10.110.8.4:9252"

  - job_name: "elasticsearch"
    file_sd_configs:
    - files:
      - 'elasticsearch_exporter.json'

  - job_name: "docker"
    file_sd_configs:
    - files:
      - 'docker_exporter.json'

  - job_name: "kube-proxy"
    file_sd_configs:
    - files:
      - 'kube-proxy.json'
    metric_relabel_configs: "{{ elasticsearch_instance_add_cluster_label + prometheus_node_metric_relabel_configs }}"

  - job_name: "kube-state-metrics"
    static_configs:
    - targets:
      - "10.110.8.4:32080" # load balancer
    metric_relabel_configs:
    - action: replace
      regex: 192\.168\.128\.47:32080
      replacement: rmdskadevdu011:32080
      source_labels:
        - instance
      target_label: instance

  - job_name: "k8stelemetry"
    static_configs:
    - targets:
      - "10.110.8.4:32081" # load balancer
    metric_relabel_configs:
    - action: replace
      regex: 192\.168\.128\.47:32081
      replacement: rmdskadevdu011:32081
      source_labels:
        - instance
      target_label: instance

  - job_name: "ceph_cluster"
    file_sd_configs:
    - files:
      - 'ceph-mgr.json'

# node exporter versions
node_exporter_version: 0.18.1-1.el7
node_exporter_apt_package: http://archive.ubuntu.com/ubuntu/pool/universe/p/prometheus-node-exporter/prometheus-node-exporter_0.18.1+ds-2_amd64.deb

thanos_query_endpoints:
