#!/usr/bin/env ansible-playbook
---
- name: Elasticsearch client access check
  hosts: all
  tasks:
  - name: Client can reach elasticsearch port
    ansible.builtin.wait_for:
      port: "{{elasticsearch_transport_port | int}}"
      host: "{{hostvars[item]['ip']}}"
      delay: 5
      timeout: 60
    loop: "{{groups[elasticsearch_node_group]}}"
  - name: Client can reach elasticsearch API port
    ansible.builtin.wait_for:
      port: "{{elasticsearch_api_port | int}}"
      host: "{{hostvars[item]['ip']}}"
      delay: 5
      timeout: 60
    loop: "{{groups[elasticsearch_node_group]}}"
  - name: Unauthorized client can access elasticsearch API
    ansible.builtin.uri:
      url: "http://{{hostvars[item]['ip']}}:{{elasticsearch_api_port}}/{{elasticsearch_health_endpoint}}"
      method: GET
      force: yes
      status_code: [200]
    loop: "{{groups[elasticsearch_node_group]}}"
