image: $SKA_K8S_TOOLS_BUILD_DEPLOY_ALPINE

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - lint
  - test

test-runner:
  stage: test
  tags:
    - ska-techops-iac-gitlab-runner
  before_script:
    - apt update
    - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip
    - unzip terraform.zip && rm terraform.zip && mv terraform /usr/bin/terraform

  variables:
    TF_HTTP_USERNAME: "domingosnunes"
    TF_HTTP_PASSWORD: "glpat-KPszpYThf1za8ZcSKrjf"
    ENVIRONMENT: "stfc-techops"
  script:
    - make orch init
    - make orch plan

include:
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/terraform.gitlab-ci.yml'
- project: 'ska-telescope/templates-repository'
  file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'