image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERRAFORM_VERSION: "1.2.8"

stages:
  - lint
  - plan
  - apply
  - staging_install
  - production_install
  - test

include:
  - local: '.gitlab/ci/e2e.gitlab-ci.yml'
  - local: '.gitlab/ci/installation.gitlab-ci.yml'
  - local: '.gitlab/ci/orchestration.gitlab-ci.yml'
  - local: '.gitlab/ci/stfc-techops.gitlab-ci.yml'
    
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/terraform.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
