image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERRAFORM_VERSION: "1.2.8"
  REQUIRED_SSH_KEYS: ska-techops.pem

.install_terraform: &install_terraform
  - apt update
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip -O terraform.zip
  - unzip terraform.zip && rm terraform.zip && mv terraform /usr/bin/terraform

.install_python_dependencies: &install_python_dependencies
  - poetry config virtualenvs.create false
  - poetry install

.install_secrets: &install_secrets
  - curl --silent "https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/load-secure-files/-/raw/main/installer" | bash
  - for SSH_KEY in $(echo $REQUIRED_SSH_KEYS | tr -d ' ' | tr ',' '\n'); do cp .secure_files/$SSH_KEY resources/keys/$SSH_KEY; done



.on_success_rules: &on_success_rules
  - when: on_success

.manual_rules: &manual_rules
  - when: manual

stages:
  - lint
  - plan
  - apply
  - staging:installation
  - staging:test
  - installation
  - test
  - e2e-tests

include:
  - local: '.gitlab/ci/e2e.gitlab-ci.yml'
  - local: '.gitlab/ci/installation.gitlab-ci.yml'
  - local: '.gitlab/ci/orchestration.gitlab-ci.yml'
  - local: '.gitlab/ci/stfc-techops.gitlab-ci.yml'
    
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/terraform.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
