image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  TERRAFORM_VERSION: "1.2.8"

stages:
  - lint
  - plan
  - apply
  - test
  - staging_install
  - staging_test
  - production_install
  - production_test

include:
  - local: '.gitlab/ci/datacentres.gitlab-ci.yml'
  - local: '.gitlab/ci/templates.gitlab-ci.yml'
  - local: '.gitlab/ci/logging.e2e.gitlab-ci.yml'
  - local: '.gitlab/ci/staging.logging.gitlab-ci.yml'
  - local: '.gitlab/ci/production.logging.gitlab-ci.yml'
    
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/terraform.gitlab-ci.yml'
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'
