debug: false

ca_host: ca
ca_cert_password: "{{ lookup('ansible.builtin.env', 'CA_CERT_PASSWORD', default=secrets['ca_cert_password']) | mandatory }}"
nexus: 192.168.113.36

elasticsearch_password: "{{ lookup('ansible.builtin.env', 'ELASTICSEARCH_PASSWORD', default=secrets['elasticsearch_password']) | mandatory }}"

logging_filebeat_oci_engine: podman
logging_filebeat_elasticsearch_password: "{{ elasticsearch_password }}"

prometheus_localuser: "{{ lookup('env', 'USER') }}"
prometheus_server_docker_tags: 'v2.37.1'
prometheus_server_title: SKA DevOps Prometheus Server
prometheus_server_memory: 16384M
prometheus_server_swapfile_path: /swapfile
prometheus_server_swapfile_size: 1000
prometheus_server_swapfile_fallocate: true
prometheus_server_kubectl_version: 'v1.22.5'
prometheus_server_kubectl_name: kubectl
prometheus_server_kubectl_install_dir: /usr/local/bin
prometheus_server_kubectl_url: 'https://storage.googleapis.com/kubernetes-release/release/{{ prometheus_server_kubectl_version }}/bin/linux/amd64/{{ prometheus_server_kubectl_name }}'
prometheus_alertmanager_docker_tags: 'v0.24.0'
prometheus_blackbox_exporter_docker_tags: 'v0.21.0'
prometheus_docker_exporter_cadvisor_docker_tags: 'v0.44.0'
prometheus_grafana_docker_tags: '9.0.0'
prometheus_grafana_influxdb: 192.168.100.5
prometheus_grafana_influxdb_db: gitlab_metrics
prometheus_thanos_docker_tags: 'v0.28.0'
