debug: false

ca_host: ca
ca_cert_password: "{{ lookup('ansible.builtin.env', 'CA_CERT_PASSWORD', default=secrets['ca_cert_password']) | mandatory }}"
nexus: 192.168.99.204  # stfc-techops nexus instance (d627d1db-a8c8-4524-b643-9c3c9c8bf967)

elasticsearch_password: "{{ lookup('ansible.builtin.env', 'ELASTICSEARCH_PASSWORD', default=secrets['elasticsearch_password']) | mandatory }}"

logging_filebeat_oci_engine: podman
logging_filebeat_elasticsearch_password: "{{ elasticsearch_password }}"

prometheus_k8s_api_server_addr: "10.200.0.63"

prometheus_k8s_external_dns_entry: k8s.stfc.skao.int

prometheus_alertmanager_url: http://monitoring.skao.stfc:9093
prometheus_url: https://monitoring.skao.stfc:9090
slack_channel: techops-alerts
slack_channel_user: techops-user-alerts

thanos_alt_name: "k8s.stfc.skao.int"

project_name: "SKA-TechOps"

prometheus_datacentre: stfc-ska-monitor

prometheus_static_node_metric_relabel_configs:
  - action: replace
    regex: 130\.246\.214\.45:9100
    replacement: terminus:9100
    source_labels:
    - instance
    target_label: instance
  - action: replace
    regex: 192\.168\.99\.194 :9100
    replacement: terminus:9100
    source_labels:
    - instance
    target_label: instance

prometheus_scrape_configs:
  - job_name: "prometheus"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"

  - job_name: "gitlab_ci_pipelines_exporter"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:8080"

  - job_name: "node"
    file_sd_configs:
    - files:
      - 'node_exporter.json'
    metric_relabel_configs: "{{ prometheus_elasticsearch_instance_add_cluster_label + prometheus_node_metric_relabel_configs }}"

  - job_name: "gitlab-runner"
    static_configs:
    - targets:
      - "10.200.0.63:9252"

  - job_name: "elasticsearch"
    file_sd_configs:
    - files:
      - 'elasticsearch_exporter.json'

  - job_name: "docker"
    file_sd_configs:
    - files:
      - 'docker_exporter.json'

  - job_name: "kube-proxy"
    file_sd_configs:
    - files:
      - 'kube-proxy.json'
    metric_relabel_configs: "{{ prometheus_elasticsearch_instance_add_cluster_label + prometheus_node_metric_relabel_configs }}"

  - job_name: "kube-state-metrics"
    static_configs:
    - targets:
      - "10.200.0.63:32080"  # load balancer
    metric_relabel_configs:
    - action: replace
      regex: 192\.168\.99\.222:32080
      replacement: systems-k8s1-loadbalancer:32080
      source_labels:
        - instance
      target_label: instance

  - job_name: "k8stelemetry"
    static_configs:
    - targets:
      - "10.200.0.63:32081"  # load balancer
    metric_relabel_configs:
    - action: replace
      regex: 192\.168\.99\.222:32081
      replacement: systems-k8s1-loadbalancer:32081
      source_labels:
        - instance
      target_label: instance

  - job_name: "ceph_cluster"
    file_sd_configs:
    - files:
      - 'ceph-mgr.json'

thanos_query_endpoints:
- 192.168.99.153:10901
- 192.168.99.31:19090 # store gateway
- dns+sdhp.stfc.skao.int:10901 # jupiter sidecar exposed
