debug: false
ansible_ssh_timeout: 60

ca_host: ca
ca_cert_password: "{{ lookup('ansible.builtin.env', 'CA_CERT_PASSWORD', default=secrets['ca_cert_password']) | mandatory }}"
nexus: 192.168.99.204  # stfc-techops nexus instance (d627d1db-a8c8-4524-b643-9c3c9c8bf967)

elasticsearch_cluster_name: "{{ ska_datacentre }}-{{ ska_environment }}-{{ ska_service }}-{{ ska_ci_pipeline_id }}"
elasticsearch_dns_name: "{{ elasticsearch_cluster_name }}-loadbalancer"
elasticsearch_password: "{{ lookup('ansible.builtin.env', 'ELASTICSEARCH_PASSWORD', default=secrets['elasticsearch_password']) | mandatory }}"
elastic_haproxy_stats_password: "{{ lookup('ansible.builtin.env', 'ELASTIC_HAPROXY_STATS_PASSWORD', default=secrets['elastic_haproxy_stats_password']) | mandatory }}"
kibana_viewer_password: "{{ lookup('ansible.builtin.env', 'KIBANA_VIEWER_PASSWORD', default=secrets['kibana_viewer_password']) | mandatory }}"
elasticsearch_memory: 8G
elasticsearch_java_mem: 4g
elasticsearch_reinstall: true
elasticsearch_clean_data_volume: true
certificates_recreate: false

# Variables required for the tests
elasticsearch_api_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_health_endpoint: "/_cat/health"
elasticsearch_nodes_endpoint: "/_cat/nodes?h=name"
elasticsearch_doc_endpoint: "/_doc/"
elasticsearch_doc_count_endpoint: "/_count"
elasticsearch_doc_delete_endpoint: "/_delete_by_query"
certificates_dir: "/etc/pki/tls/private"