debug: false
ansible_ssh_timeout: 60

elasticsearch_cluster_name: elastic-e2e-test

# Required by testing playbooks
# TODO: Move tests to elastic stack playbooks
elasticsearch_api_port: 9200
elasticsearch_transport_port: 9300
elasticsearch_health_endpoint: "/_cat/health"
elasticsearch_nodes_endpoint: "/_cat/nodes?h=name"
elasticsearch_doc_endpoint: "/_doc/"
elasticsearch_doc_count_endpoint: "/_count"
elasticsearch_doc_delete_endpoint: "/_delete_by_query"