all:
  children:
    cental-monitoring: null
  hosts: {}
cental-monitoring:
  children:
    cental-monitoring_data: null
    cental-monitoring_kibana: null
    cental-monitoring_master: null
  hosts: {}
cental-monitoring_data:
  hosts: {}
cental-monitoring_kibana:
  hosts: {}
cental-monitoring_master:
  hosts:
    cental-monitoring_master_i00:
      ansible_host: 192.168.99.25
      ansible_python_interpreter: python3
      ansible_ssh_common_args: -o ControlPersist=30m -o StrictHostKeyChecking=no -o
        ProxyCommand="ssh -i "./keys/ska-techops.pem" -W %h:%p -q ubuntu@130.246.214.45"
        -v
      ansible_ssh_private_key_file: ./keys/ska-techops.pem
      ansible_user: ubuntu
      volumes:
      - device: /dev/vdb
        file_system: ext4
        id: 03b609ec-37fa-448e-b78e-d9d63b6bea3f
        mount_point: /usr/share/elasticsearch/data
        name: cental-monitoring_master_i00-data-vol
    cental-monitoring_master_i01:
      ansible_host: 192.168.99.236
      ansible_python_interpreter: python3
      ansible_ssh_common_args: -o ControlPersist=30m -o StrictHostKeyChecking=no -o
        ProxyCommand="ssh -i "./keys/ska-techops.pem" -W %h:%p -q ubuntu@130.246.214.45"
        -v
      ansible_ssh_private_key_file: ./keys/ska-techops.pem
      ansible_user: ubuntu
      volumes:
      - device: /dev/vdb
        file_system: ext4
        id: 29c5b131-207e-4e8d-9674-bd2599d709cc
        mount_point: /usr/share/elasticsearch/data
        name: cental-monitoring_master_i01-data-vol
    cental-monitoring_master_i02:
      ansible_host: 192.168.99.24
      ansible_python_interpreter: python3
      ansible_ssh_common_args: -o ControlPersist=30m -o StrictHostKeyChecking=no -o
        ProxyCommand="ssh -i "./keys/ska-techops.pem" -W %h:%p -q ubuntu@130.246.214.45"
        -v
      ansible_ssh_private_key_file: ./keys/ska-techops.pem
      ansible_user: ubuntu
      volumes:
      - device: /dev/vdb
        file_system: ext4
        id: eba2d629-c3b8-4fc2-b3e1-1761ec896e4a
        mount_point: /usr/share/elasticsearch/data
        name: cental-monitoring_master_i02-data-vol
