.ca_e2e:
  stage: test
  extends:
    - .stfc_techops
    - .orchestration_dependencies
  variables:
    ENVIRONMENT: e2e
    REQUIRED_SSH_KEYS: "ska-ser-ca.pem,ska-e2e-test.pem"
    SERVICE: ca
    BATS_TEST_SUITES: "unit setup $SERVICE"
  environment:
    name: stfc-techops-e2e-ca/$CI_COMMIT_REF_SLUG
    deployment_tier: testing
    auto_stop_in: 2 hours
    on_stop: ca_e2e_tests_cleanup

ca_e2e_tests:
  extends:
    - .ca_e2e
  environment:
    action: start
  allow_failure: true
  artifacts:
    when: always
    paths:
      - build/
      - tests/e2e/build
  script:
    - !reference [.orchestration_dependencies, script]
    - make im-test
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "ca_e2e_tests"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
      allow_failure: true

ca_e2e_tests_cleanup:
  extends:
    - .ca_e2e
  environment:
    action: stop
  needs:
    - ca_e2e_tests
  artifacts:
    paths:
      - build/
      - tests/e2e/build
  script:
    - !reference [.orchestration_dependencies, script]
    - make im-test-cleanup
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "ca_e2e_tests"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
