.start_e2e_tests:
  extends:
    - .orchestration_base_job
  stage: e2e-tests
  environment:
    action: start
  allow_failure: true
  variables:
    BATS_TEST_SUITES: "unit setup $SERVICE"
  artifacts:
    paths:
      - build/
      - tests/e2e/build
  script:
    - echo 'make im-test'

.stop_e2e_tests:
  extends:
    - .orchestration_base_job
  stage: e2e-tests
  environment:
    action: stop
  artifacts:
    paths:
      - build/
      - tests/e2e/build
  script:
    - echo 'make im-test-cleanup'
  when: manual