.start_e2e_tests:
  extends:
    - .orchestration_base_job
  stage: e2e-tests
  environment:
    action: start
  allow_failure: true
  variables:
    JOB: e2e
    BATS_TEST_SUITES: "unit setup $SERVICE"
  artifacts:
    paths:
      - build/
      - tests/e2e/build
  script:
    - echo 'make im-test'
  rules:
    - !reference [.automatic_rules]

.stop_e2e_tests:
  extends:
    - .orchestration_base_job
  stage: e2e-tests
  environment:
    action: stop
  variables:
    JOB: e2e
  artifacts:
    paths:
      - build/
      - tests/e2e/build
  script:
    - echo 'make im-test-cleanup'
  rules:
    - !reference [.manual_rules]