.installation_base_job:
  stage: installation
  before_script:
    - !reference [.install_python_dependencies]
    - !reference [.install_secrets]

.logging_install_task:
  variables:
    REINSTALL: "false"
  script: |
    if [ "$REINSTALL" = "true" ]; then
    cat <<EOF > cicd-extra-vars.yml
    elasticsearch_reinstall: true
    elasticsearch_exporter_reinstall: true
    kibana_reinstall: true
    EOF
      echo "ANSIBLE_PLAYBOOK_ARGUMENTS='-e @$(pwd)/cicd-extra-vars.yml' make playbooks logging install"
    else
      echo "make playbooks logging install"
    fi

.logging_destroy_task:
  script:
    - echo 'make playbooks logging destroy'

.logging_test_task:
  stage: test
  script:
    - echo 'make playbooks logging test'