.production_monitoring:
  extends: .stfc_techops
  variables:
    ENVIRONMENT: production
    REQUIRED_SSH_KEYS: "ska-techops.pem"
    SERVICE: monitoring
    PLAYBOOKS_HOSTS: "stfc-techops-production-monitoring-prometheus,stfc-techops-production-monitoring-thanos"
  environment:
    name: stfc-techops-production-monitoring
    deployment_tier: production

production_monitoring_plan:
  extends:
    - .production_monitoring
    - .orchestration_plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "production_monitoring_orchestration"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
      allow_failure: true

production_monitoring_apply:
  extends:
    - .production_monitoring
    - .orchestration_apply
  needs:
    - production_monitoring_plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "production_monitoring_orchestration"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual

production_monitoring_install:
  stage: production_install
  extends:
    - .production_monitoring
    - .installation_dependencies
  needs:
    - staging_monitoring_install
    - staging_monitoring_test
  variables:
    REINSTALL: "false"
  script:
    - make orch generate-inventory
    - make playbooks oci docker
    - export KUBECONFIG=$KUBECONFIG_STFC
    - PLAYBOOKS_HOSTS=prometheus make playbooks monitoring prometheus
    - PLAYBOOKS_HOSTS=prometheus make playbooks monitoring grafana
    - PLAYBOOKS_HOSTS=prometheus make playbooks monitoring alertmanager
    - PLAYBOOKS_HOSTS=prometheus make playbooks monitoring grafana
    - PLAYBOOKS_HOSTS=thanos make playbooks monitoring thanos
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "production_monitoring_install"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
      allow_failure: true

production_monitoring_test:
  stage: production_test
  extends:
    - .production_monitoring
    - .installation_dependencies
  needs:
    - production_monitoring_install
  script:
    - make orch generate-inventory
    - make playbooks monitoring test-prometheus
    - make playbooks monitoring test-thanos 
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $SCHEDULED_JOB == "production_monitoring_install"
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success
