.staging_logging:
  extends: .stfc_techops
  variables:
    ENVIRONMENT: staging
    REQUIRED_SSH_KEYS: "ska-staging.pem"
    SERVICE: logging
    PLAYBOOKS_HOSTS: "stfc-techops-staging-logging"
  environment:
    name: stfc-techops-staging-logging
    deployment_tier: staging

staging_logging_plan:
  extends:
    - .staging_logging
    - .orchestration_plan

staging_logging_apply:
  extends:
    - .staging_logging
    - .orchestration_apply
  needs:
    - staging_logging_plan

staging_logging_install:
  stage: staging_install
  extends:
    - .staging_logging
    - .installation_dependencies
  variables:
    REINSTALL: "false"
  script:
    - echo "make playbooks logging install ANSIBLE_PLAYBOOK_ARGUMENTS='-e elasticsearch_reinstall=${REINSTALL} -e elasticsearch_exporter_reinstall=${REINSTALL} -e kibana_reinstall=${REINSTALL}'"
  rules:
    - !reference [.automatic_trigger]

staging_logging_destroy:
  stage: staging_install
  extends:
    - .staging_logging
    - .installation_dependencies
  script:
    - echo 'make playbooks logging destroy'
  rules:
    - !reference [.dettached_trigger]

staging_logging_test:
  stage: staging_test
  extends:
    - .staging_logging
    - .installation_dependencies
  script:
    - echo 'make playbooks logging test'
  needs:
    - staging_logging_install
